package com.engine.mnsfz.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CLASSFY.
 */
public class classfy {

    private String title;
    private String href;
    private String src;

    public classfy() {
    }

    public classfy(String href) {
        this.href = href;
    }

    public classfy(String title, String href, String src) {
        this.title = title;
        this.href = href;
        this.src = src;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getHref() {
        return href;
    }

    public void setHref(String href) {
        this.href = href;
    }

    public String getSrc() {
        return src;
    }

    public void setSrc(String src) {
        this.src = src;
    }

}
