package com.engine.mnsfz.greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

<<<<<<< HEAD
import com.engine.mnsfz.greendao.PersonImageDao;
=======
import com.engine.mnsfz.greendao.ImageBeanDao;
import com.engine.mnsfz.greendao.ModelBeanDao;
>>>>>>> b2726ae215183b4e84a074f89d8a3adf1aad13c5

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
<<<<<<< HEAD
        PersonImageDao.createTable(db, ifNotExists);
=======
        ImageBeanDao.createTable(db, ifNotExists);
        ModelBeanDao.createTable(db, ifNotExists);
>>>>>>> b2726ae215183b4e84a074f89d8a3adf1aad13c5
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
<<<<<<< HEAD
        PersonImageDao.dropTable(db, ifExists);
=======
        ImageBeanDao.dropTable(db, ifExists);
        ModelBeanDao.dropTable(db, ifExists);
>>>>>>> b2726ae215183b4e84a074f89d8a3adf1aad13c5
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
<<<<<<< HEAD
        registerDaoClass(PersonImageDao.class);
=======
        registerDaoClass(ImageBeanDao.class);
        registerDaoClass(ModelBeanDao.class);
>>>>>>> b2726ae215183b4e84a074f89d8a3adf1aad13c5
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
