package com.engine.mnsfz.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.engine.mnsfz.greendao.classfy;

import com.engine.mnsfz.greendao.classfyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig classfyDaoConfig;

    private final classfyDao classfyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        classfyDaoConfig = daoConfigMap.get(classfyDao.class).clone();
        classfyDaoConfig.initIdentityScope(type);

        classfyDao = new classfyDao(classfyDaoConfig, this);

        registerDao(classfy.class, classfyDao);
    }
    
    public void clear() {
        classfyDaoConfig.getIdentityScope().clear();
    }

    public classfyDao getClassfyDao() {
        return classfyDao;
    }

}
