package com.engine.mnsfz.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MODEL_BEAN.
 */
public class ModelBean {

    private String title;
    private String src;
    private Long time;

    public ModelBean() {
    }

    public ModelBean(String src) {
        this.src = src;
    }

    public ModelBean(String title, String src, Long time) {
        this.title = title;
        this.src = src;
        this.time = time;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSrc() {
        return src;
    }

    public void setSrc(String src) {
        this.src = src;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
